language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- export DISPLAY=:0.0
- bundle install
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test

